spec:
  name: ninjaone-mcp
  services:
    - name: ninjaone-mcp
      github:
        repo: wyre-technology/ninjaone-mcp
        branch: main
        deploy_on_push: true
      dockerfile_path: Dockerfile
      http_port: 8080
      instance_count: 1
      instance_size_slug: basic-xxs
      envs:
        - key: NINJAONE_CLIENT_ID
          scope: RUN_TIME
          type: SECRET
        - key: NINJAONE_CLIENT_SECRET
          scope: RUN_TIME
          type: SECRET
        - key: NINJAONE_REGION
          scope: RUN_TIME
          type: SECRET
        - key: MCP_TRANSPORT
          scope: RUN_TIME
          value: http
        - key: AUTH_MODE
          scope: RUN_TIME
          value: gateway
        - key: NODE_ENV
          scope: RUN_TIME
          value: production
      health_check:
        http_path: /health
        initial_delay_seconds: 10
        period_seconds: 30
        timeout_seconds: 5
        success_threshold: 1
        failure_threshold: 3
